[cadastro_form id='TesteDeForm']

[cadastro_nome placeholder='nome do cliente']
[cadastro_data]
[cadastro_login  placeholder='informe seu login']
[cadastro_senha placeholder='informe sua senha']
[cadastro_rg placeholder='digite seu rg']
[cadastro_cpf placeholder='digite seu cpf']
[cadastro_profissao label='selecione a profissão do cliente: ']
[cadastro_email placeholder='digite seu e-mail']
[cadastro_telefone placeholder='telefone']
[cadastro_rua label='rua']
[cadastro_numero label='numero']
[cadastro_bairro label='bairro']
[cadastro_complemento label='complemento']
[cadastro_cidade label='cidade']
[cadastro_estado label='estado']
[cadastro_form_btn]

[/cadastro_form]
